site_name: DSaA
nav:
    - 首页: index.md
    - 第一章 引论: Chapter1/index.md
    - 第二章 算法分析: Chapter2/index.md
    - 第三章 表，栈和队列: Chapter3/index.md
    - 第四章 树: Chapter4/index.md
    - 第五章 散列: Chapter5/index.md
    - 第六章 优先队列（堆）: Chapter6/index.md
    - 第七章 排序: Chapter7/index.md
    - 第八章 不相交集 ADT: Chapter8/index.md
    - 第九章 图论算法: Chapter9/index.md
    - 第十章 算法设计技巧: Chapter10/index.md
    - 第十一章 摊还分析: Chapter11/index.md
    - 第十二章 高级数据结构及其实现: Chapter12/index.md
theme: readthedocs
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
